package com.n3rditorium.pocketdoggie.persistence;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.n3rditorium.pocketdoggie.persistence.DogDB;
import com.n3rditorium.pocketdoggie.persistence.MetricDB;

import com.n3rditorium.pocketdoggie.persistence.DogDBDao;
import com.n3rditorium.pocketdoggie.persistence.MetricDBDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dogDBDaoConfig;
    private final DaoConfig metricDBDaoConfig;

    private final DogDBDao dogDBDao;
    private final MetricDBDao metricDBDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dogDBDaoConfig = daoConfigMap.get(DogDBDao.class).clone();
        dogDBDaoConfig.initIdentityScope(type);

        metricDBDaoConfig = daoConfigMap.get(MetricDBDao.class).clone();
        metricDBDaoConfig.initIdentityScope(type);

        dogDBDao = new DogDBDao(dogDBDaoConfig, this);
        metricDBDao = new MetricDBDao(metricDBDaoConfig, this);

        registerDao(DogDB.class, dogDBDao);
        registerDao(MetricDB.class, metricDBDao);
    }
    
    public void clear() {
        dogDBDaoConfig.getIdentityScope().clear();
        metricDBDaoConfig.getIdentityScope().clear();
    }

    public DogDBDao getDogDBDao() {
        return dogDBDao;
    }

    public MetricDBDao getMetricDBDao() {
        return metricDBDao;
    }

}
