package com.n3rditorium.pocketdoggie.persistence;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "DEED_DB".
 */
public class DeedDB {

    private Long id;
    private Long dogId;
    private Integer type;
    private String description;
    private Boolean inside;
    private Long timestamp;
    private Long latitude;
    private Long longitude;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public DeedDB() {
    }

    public DeedDB(Long id) {
        this.id = id;
    }

    public DeedDB(Long id, Long dogId, Integer type, String description, Boolean inside, Long timestamp, Long latitude, Long longitude) {
        this.id = id;
        this.dogId = dogId;
        this.type = type;
        this.description = description;
        this.inside = inside;
        this.timestamp = timestamp;
        this.latitude = latitude;
        this.longitude = longitude;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getDogId() {
        return dogId;
    }

    public void setDogId(Long dogId) {
        this.dogId = dogId;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Boolean getInside() {
        return inside;
    }

    public void setInside(Boolean inside) {
        this.inside = inside;
    }

    public Long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

    public Long getLatitude() {
        return latitude;
    }

    public void setLatitude(Long latitude) {
        this.latitude = latitude;
    }

    public Long getLongitude() {
        return longitude;
    }

    public void setLongitude(Long longitude) {
        this.longitude = longitude;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
