package com.n3rditorium.pocketdoggie.persistence;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "DOG_DB".
 */
public class DogDB {

    private Long id;
    private String identifier;
    private String name;
    private String description;
    private Long birthday;
    private Integer currentHeightId;
    private Integer weight;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public DogDB() {
    }

    public DogDB(Long id) {
        this.id = id;
    }

    public DogDB(Long id, String identifier, String name, String description, Long birthday, Integer currentHeightId, Integer weight) {
        this.id = id;
        this.identifier = identifier;
        this.name = name;
        this.description = description;
        this.birthday = birthday;
        this.currentHeightId = currentHeightId;
        this.weight = weight;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIdentifier() {
        return identifier;
    }

    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Long getBirthday() {
        return birthday;
    }

    public void setBirthday(Long birthday) {
        this.birthday = birthday;
    }

    public Integer getCurrentHeightId() {
        return currentHeightId;
    }

    public void setCurrentHeightId(Integer currentHeightId) {
        this.currentHeightId = currentHeightId;
    }

    public Integer getWeight() {
        return weight;
    }

    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
