package com.n3rditorium.pocketdoggie.persistence;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "METRIC_DB".
 */
public class MetricDB {

    private Long id;
    private Long dogId;
    private Integer value;
    private Integer unitId;
    private Long timestamp;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public MetricDB() {
    }

    public MetricDB(Long id) {
        this.id = id;
    }

    public MetricDB(Long id, Long dogId, Integer value, Integer unitId, Long timestamp) {
        this.id = id;
        this.dogId = dogId;
        this.value = value;
        this.unitId = unitId;
        this.timestamp = timestamp;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getDogId() {
        return dogId;
    }

    public void setDogId(Long dogId) {
        this.dogId = dogId;
    }

    public Integer getValue() {
        return value;
    }

    public void setValue(Integer value) {
        this.value = value;
    }

    public Integer getUnitId() {
        return unitId;
    }

    public void setUnitId(Integer unitId) {
        this.unitId = unitId;
    }

    public Long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
